version: "3.9"

services:
  flask_app:
    build: .
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    volumes:
      - .:/app       # Optional: live code updates
    environment:
      - FLASK_ENV=development
